
'''Description: PEuler 29 - Distinct powers

   Q: How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

   See: https://projecteuler.net/problem=29

   Date: August 26, 2019
'''

def main():
    terms = {}

    for a in range(2, 6):
        for b in range(2, 6):
            terms[a**b] = a**b
    print(len(terms))

main()
